### ISSUE TITLE
npe when joining servers

### ISSUE THREAD

**Issue by S-B99** [S-B99/KAMI#296]
happens even with all modules off

![Screenshot_20191217_211628](https://user-images.githubusercontent.com/17222512/71050184-8142fb80-2112-11ea-9498-88f618a38173.png)

asflkasf fuckianf asfa kill me a;i

**Comment by S-B99** [comment]
note: fixed if you reset to commit 706a1a35a1d6eec3b8d31406a06f0b598e4a6696

todo: somebody check which commit broke it

**Comment by S-B99** [comment]
if you want a visual 
![Screenshot_20191217_212850](https://user-images.githubusercontent.com/17222512/71050807-3c1fc900-2114-11ea-8951-0352cb103f4e.png)

**Comment by S-B99** [comment]
ok wtf

local changes i guess

**Comment by S-B99** [comment]
i think remote changes work???

**Comment by S-B99** [comment]
611817ee11ec9a3cd40d6fbbc8c72d0357e332f4 breaks this, checked this time

**Comment by EmotionalLove** [comment]
if there's an npe paste me your latest.log

**Comment by S-B99** [comment]
O I went to sleep sec

**Comment by S-B99** [comment]
```
[22:34:41] [main/ERROR] [net.minecraft.client.network.ServerPinger]: Can't ping 147.135.8.3:25586: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[22:34:41] [main/ERROR] [net.minecraft.client.network.ServerPinger]: Can't ping crystalpvp.cc: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[22:34:42] [main/ERROR] [net.minecraft.client.network.ServerPinger]: Can't ping 2b2t.org: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[22:34:43] [main/INFO] [net.minecraft.client.multiplayer.GuiConnecting]: Connecting to 2b2t.org, 25565
[22:34:44] [Discord-RPC-Callback-Handler/INFO] [STDERR]: [me.zeroeightsix.kami.DiscordPresence:lambda$start$1:84]: java.lang.NullPointerException
[22:34:44] [Discord-RPC-Callback-Handler/INFO] [STDERR]: [me.zeroeightsix.kami.DiscordPresence:lambda$start$1:84]:      at me.zeroeightsix.kami.module.ModuleManager.getModuleByName(ModuleManager.java:122)
[22:34:44] [Discord-RPC-Callback-Handler/INFO] [STDERR]: [me.zeroeightsix.kami.DiscordPresence:lambda$start$1:84]:      at me.zeroeightsix.kami.DiscordPresence.lambda$start$1(DiscordPresence.java:61)
[22:34:44] [Discord-RPC-Callback-Handler/INFO] [STDERR]: [me.zeroeightsix.kami.DiscordPresence:lambda$start$1:84]:      at java.lang.Thread.run(Thread.java:748)
```
It looks like it's being caused by discord rpc but it doesn't happen until that commit I sent ;-;

**Comment by EmotionalLove** [comment]
i’ll fix rn
